root WARNING tsvr.py:235 2011-09-04 00:24:19,982 2817:140251509765888	get_items in new_user fail: [Errno 111] Connection refused
root WARNING tsvr.py:235 2011-09-04 00:24:21,002 2817:140251509765888	get_items in new_user fail: could not connect to 127.0.0.1:27017: [Errno 111] Connection refused
root WARNING tsvr.py:235 2011-09-04 00:24:22,004 2817:140251509765888	get_items in new_user fail: could not connect to 127.0.0.1:27017: [Errno 111] Connection refused
